// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";

function Home$Homepage(Props) {
  return React.createElement("h1", undefined, "Can you see me ?");
}

var Homepage = {
  make: Home$Homepage
};

function react(param) {
  var root = document.querySelector("#reactRoot");
  if (!(root == null)) {
    ReactDom.render(React.createElement("div", undefined, React.createElement(Home$Homepage, {})), root);
    return ;
  }
  
}

export {
  Homepage ,
  react ,
  
}
/* react Not a pure module */
